config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('almanac.urls')),
    # path('', RedirectView.as_view(url='almanac/')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

overtrick/almanac/urls.py
from django.urls import path

from . import views

app_name = 'almanac'
urlpatterns = [
    path('sessions/', views.list, name='session_list'),
    path('sessions/<int:session_id>/', views.detail, name='session_detail'),
]

overtrick/almanac/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Session(models.Model):
    class Time(models.TextChoices):
        MORNING = 'M', _('Morning')
        AFTERNOON = 'A', _('Afternoon')
        EVENING = 'E', _('Evening')

    club = models.CharField(max_length=20)
    date = models.DateField()
    time = models.CharField(
        max_length=1,
        choices=Time.choices,
        default=Time.EVENING,
    )
    event = models.CharField(max_length=40)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['club', 'date', 'time', 'event'],
                name='unique session'
            )
        ]
        ordering = ['-date', 'time']

    def __str__(self):
        return f'{self.club}: {self.date} {self.time} {self.event}'

overtrick/pairs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from almanac.models import Session


class Pair(models.Model):
    class Orientation(models.TextChoices):
        NORTH = 'NS', _('North/South')
        EAST = 'EW', _('East/West')

    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    orientation = models.CharField(
        max_length=2,
        choices=Orientation.choices,
        default=Orientation.NORTH,
    )
    number = models.IntegerField()
    player_a = models.CharField(max_length=25)
    player_b = models.CharField(max_length=25)
    points = models.FloatField()

    @property
    def player_names(self):
        return f'{self.player_a} and {self.player_b}'

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['session', 'orientation', 'number'],
                name='unique pair'
            )
        ]
        ordering = ['-orientation', '-points']

    def __str__(self):
        return f'{self.orientation} #{self.number} ' \
               f'{self.player_a}/{self.player_b}'

overtrick/almanac/views.py
from django.shortcuts import get_object_or_404, render

from .models import Session


def list(request):
    return render(
        request,
        'session_list.html',
        {'sessions': Session.objects.order_by('-date')[1:4]}
    )


def detail(request, session_id):
    return render(
        request,
        'session_detail.html',
        {'session': get_object_or_404(Session, pk=session_id)}
    )

overtrick/pairs/views.py
from django.shortcuts import render

# Create your views here.

overtrick/almanac/templates/session_detail.html
{% extends "layout.html" %}

{% block subtitle %}Pairs |{% endblock subtitle %} Overtrick

{% block header-left %}
    {{ session.event }}
{% endblock header-left %}

{% block header-right %}
    {{ session.get_time_display }}, {{ session.date }}
{% endblock header-right %}

{% block main %}
    <table class="table" >
        <tbody >
        <tr >
            <th scope="col" >Pair</th >
            <th scope="col" >Players</th >
            <th scope="col" >Points</th >
        </tr >
        {% for pair in session.pair_set.all %}
            <tr >
                <td >{{ pair.number }}</td >
                <td >{{ pair.player_names }}</td >
                <td >{{ pair.points|floatformat }}</td >
            </tr >
        {% endfor %}
        </tbody >
    </table >
{% endblock main %}

overtrick/almanac/templates/session_list.html
{% extends "layout.html" %}

{% block subtitle %}Sessions |{% endblock subtitle %}

{% block header-left %}Wellington Bridge Club{% endblock header-left %}

{% block main %}
    <table class="table table-hover" >
        <tbody >
        <tr >
            <th scope="col" >Date</th >
            <th scope="col" >Time</th >
            <th scope="col" >Event</th >
        </tr >
        {% for session in sessions %}
            <tr onclick="window.location='{% url "almanac:session_detail" session.id %}';" >
                <td >{{ session.date }}</td >
                <td >{{ session.get_time_display }}</td >
                <td >{{ session.event }}</td >
            </tr >
        {% endfor %}
        </tbody >
    </table >
{% endblock main %}

overtrick/templates/base.html
<!DOCTYPE html>
<html lang="en" >

{% load static %}

<head >
  <meta charset="utf-8" >
  <meta name="viewport" content="width=device-width, initial-scale=1" >

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'overtrick/css/base.css' %}" >
  {% block stylesheets %}{% endblock stylesheets %}
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300" rel="stylesheet" >

  <title >{% block title %}{% endblock title %}</title >
  <link rel="shortcut icon" type="image/svg+xml" href="{% static 'overtrick/icons/favicon.svg' %}" />
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'overtrick/icons/favicon-32x32.png' %}" >
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'overtrick/icons/favicon-16x16.png' %}" >
  <link rel="shortcut icon" href="{% static 'overtrick/icons/favicon.ico' %}" >
</head >
<body >

<div id="content" >
  {% block content %}{% endblock content %}
</div >

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</body >
</html >

overtrick/templates/layout.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% block subtitle %}{% endblock subtitle %} Overtrick
{% endblock title %}

{% block stylesheets %}
    <link rel="stylesheet"
          href="{% static 'overtrick/css/social-circles.css' %}" >
{% endblock stylesheets %}

{% block content %}
    <div class="row" >
        <div id="nav-sidebar"
             class="col-3 d-flex flex-column position-fixed h-100 px-5 py-3 bg-color-dark" >
            <h3 class="pt-3 pb-2" >
                <a href="{% url 'almanac:session_list' %}" >Overtrick</a >
            </h3 >

            <hr />

            <ul id="sidebar-links" class="list-group list-group-flush ps-0" >
                <li class="list-group-item bg-color-dark ps-0" >
                    <a href="{% url 'almanac:session_list' %}" >
                        Sessions
                    </a >
                </li >
                <li class="list-group-item bg-color-dark ps-0" >
                    Players
                </li >
            </ul >
            <hr />

            <footer class="mt-auto text-center" >
                <div id="calendar" class="card mb-5 bg-color-dark" >
                    <div class="card-body" >
                        <h5 class="card-title" >Calendar</h5 >
                        <p class="card-text" ></p >
                    </div >
                </div >

                <div >
                    <a class="icon-linkedin social-button borderless"
                       href="https://www.linkedin.com/in/katemckenzie/" >
                    </a >
                    <a class="icon-github social-button borderless"
                       href="https://github.com/katemakescode/mercantile" >
                    </a >
                </div >

                <small class="text-muted" >
                    <a href="https://behind-the-web.herokuapp.com/" >Crafted by
                        Kate</a >
                    &bull; Powered by Django
                </small >
            </footer >
        </div >

        <section id="main" class="container-fluid col-9 offset-3 px-4 py-4" >
            <header class="row h4" >
                <div class="col" >
                    {% block header-left %}{% endblock header-left %}
                </div >
                <div class="col align-right" >
                    {% block header-right %}{% endblock header-right %}
                </div >
            </header >
            <hr />
            {% block main %}{% endblock main %}
        </section >
    </div >
{% endblock content %}